"""The synthetic firm's relational data (ARCHITECTURE section 2).

Working rule 7: synthetic data only. Every row here is generated by
`app/scripts/seed.py` with a fixed random seed.

Identifiers are readable strings ("CL-0001", "AC-00001") rather than surrogate
integers or UUIDs, because eval datasets reference them directly and a failing
SQL case is much easier to read when the ids mean something.

Enumerated values use TEXT plus a CHECK constraint rather than a Postgres ENUM
type: adding a value to a native enum needs its own migration and cannot run
inside a transaction in older versions, while a CHECK is a one-line alter.
"""

from datetime import date
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Date,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

# --- Allowed values, mirrored into CHECK constraints -------------------------
CLIENT_SEGMENTS = ("retail", "affluent", "hnw", "uhnw")
ACCOUNT_TYPES = ("ISA", "SIPP", "GIA", "JISA", "TRUST")
ACCOUNT_STATUSES = ("active", "closed", "suspended")
# Drives suitability rules: an execution-only account must never be rebalanced
# by the action agent.
MANDATES = ("advisory", "discretionary", "execution_only")
ASSET_CLASSES = ("equity", "bond", "fund", "etf", "cash", "alternative")
RISK_TOLERANCES = ("conservative", "balanced", "growth", "aggressive")
INVESTMENT_OBJECTIVES = ("income", "growth", "balanced", "preservation")
CAPACITY_FOR_LOSS = ("low", "medium", "high")
TRANSACTION_TYPES = ("buy", "sell", "dividend", "fee", "deposit", "withdrawal")
TASK_STATUSES = ("open", "in_progress", "done", "cancelled")

# Transaction types where money leaves the account. Drives the sign constraint
# on `transactions.amount`.
OUTFLOW_TYPES = ("buy", "withdrawal", "fee")

# Money: 18 digits with 2 decimals for amounts, 6 for unit prices and
# quantities (fractional shares and fund units are routine).
_AMOUNT = Numeric(18, 2)
_UNITS = Numeric(18, 6)


def _in(column: str, values: tuple[str, ...], name: str) -> CheckConstraint:
    allowed = ", ".join(f"'{v}'" for v in values)
    return CheckConstraint(f"{column} IN ({allowed})", name=name)


class Client(Base, TimestampMixin):
    """A (fictional) client of the firm."""

    __tablename__ = "clients"
    __table_args__ = (_in("segment", CLIENT_SEGMENTS, "segment"),)

    id: Mapped[str] = mapped_column(String(16), primary_key=True)
    full_name: Mapped[str] = mapped_column(Text, nullable=False)
    email: Mapped[str | None] = mapped_column(Text)
    date_of_birth: Mapped[date | None] = mapped_column(Date)
    country: Mapped[str | None] = mapped_column(String(2))
    segment: Mapped[str] = mapped_column(String(16), nullable=False)
    adviser: Mapped[str | None] = mapped_column(Text)
    onboarded_at: Mapped[date | None] = mapped_column(Date)

    accounts: Mapped[list["Account"]] = relationship(back_populates="client")
    risk_profile: Mapped["RiskProfile | None"] = relationship(back_populates="client")


class RiskProfile(Base, TimestampMixin):
    """One current suitability assessment per client.

    Everything the action agent must respect before proposing a trade lives
    here, and only here. Mirroring any of it onto `clients` would give the
    suitability guardrail two sources of truth with no rule for which wins.
    """

    __tablename__ = "risk_profiles"
    __table_args__ = (
        _in("tolerance", RISK_TOLERANCES, "tolerance"),
        _in("investment_objective", INVESTMENT_OBJECTIVES, "investment_objective"),
        # Nullable column: a CHECK passes on NULL, so this constrains the
        # values without making the field mandatory.
        _in("capacity_for_loss", CAPACITY_FOR_LOSS, "capacity_for_loss"),
        CheckConstraint("score BETWEEN 1 AND 100", name="score_range"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    # Unique, so the relationship above is genuinely one-to-one.
    client_id: Mapped[str] = mapped_column(
        ForeignKey("clients.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    tolerance: Mapped[str] = mapped_column(String(16), nullable=False)
    investment_objective: Mapped[str] = mapped_column(String(16), nullable=False)
    score: Mapped[int] = mapped_column(Integer, nullable=False)
    horizon_years: Mapped[int | None] = mapped_column(Integer)
    capacity_for_loss: Mapped[str | None] = mapped_column(String(16))

    # Client-specific mandate limits, e.g.
    #   {"exclude_sectors": ["tobacco"], "max_single_holding_pct": 10}
    # JSONB rather than columns because the shape varies per client and the
    # action agent reads it as a whole before proposing a rebalance.
    restrictions: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, server_default="{}")

    # When the assessment was made, and when the next one falls due. Two dates,
    # not one: "overdue for review" is a query the task tool needs to answer.
    assessed_at: Mapped[date | None] = mapped_column(Date)
    next_review_date: Mapped[date | None] = mapped_column(Date)

    client: Mapped[Client] = relationship(back_populates="risk_profile")


class Account(Base, TimestampMixin):
    """A client account. `mandate` gates what the action agent may propose."""

    __tablename__ = "accounts"
    __table_args__ = (
        _in("account_type", ACCOUNT_TYPES, "account_type"),
        _in("status", ACCOUNT_STATUSES, "status"),
        _in("mandate", MANDATES, "mandate"),
        Index("ix_accounts_client_id", "client_id"),
    )

    id: Mapped[str] = mapped_column(String(16), primary_key=True)
    client_id: Mapped[str] = mapped_column(
        ForeignKey("clients.id", ondelete="CASCADE"), nullable=False
    )
    account_type: Mapped[str] = mapped_column(String(16), nullable=False)
    mandate: Mapped[str] = mapped_column(String(16), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False, server_default="active")
    base_currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="GBP")
    opened_at: Mapped[date | None] = mapped_column(Date)

    client: Mapped[Client] = relationship(back_populates="accounts")
    holdings: Mapped[list["Holding"]] = relationship(back_populates="account")


class Instrument(Base, TimestampMixin):
    """A tradable instrument. Ids are synthetic, ISIN-shaped but not real."""

    __tablename__ = "instruments"
    __table_args__ = (_in("asset_class", ASSET_CLASSES, "asset_class"),)

    id: Mapped[str] = mapped_column(String(16), primary_key=True)
    ticker: Mapped[str | None] = mapped_column(String(16))
    name: Mapped[str] = mapped_column(Text, nullable=False)
    asset_class: Mapped[str] = mapped_column(String(16), nullable=False)
    sector: Mapped[str | None] = mapped_column(Text)
    region: Mapped[str | None] = mapped_column(Text)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="GBP")
    # Annual fee as a decimal fraction, e.g. 0.0075 for 0.75%.
    ongoing_charge: Mapped[Decimal | None] = mapped_column(Numeric(6, 4))


class Holding(Base, TimestampMixin):
    """A current position. One row per account and instrument."""

    __tablename__ = "holdings"
    __table_args__ = (
        UniqueConstraint("account_id", "instrument_id", name="account_instrument"),
        Index("ix_holdings_account_id", "account_id"),
        Index("ix_holdings_instrument_id", "instrument_id"),
        CheckConstraint("quantity >= 0", name="quantity_non_negative"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    account_id: Mapped[str] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False
    )
    instrument_id: Mapped[str] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT"), nullable=False
    )
    quantity: Mapped[Decimal] = mapped_column(_UNITS, nullable=False)
    average_cost: Mapped[Decimal | None] = mapped_column(_UNITS)
    as_of: Mapped[date] = mapped_column(Date, nullable=False)

    account: Mapped[Account] = relationship(back_populates="holdings")
    instrument: Mapped[Instrument] = relationship()


class Transaction(Base, TimestampMixin):
    """Two years of account activity."""

    __tablename__ = "transactions"
    __table_args__ = (
        _in("transaction_type", TRANSACTION_TYPES, "transaction_type"),
        # The sign of `amount` must agree with the type: buys, withdrawals and
        # fees take money out, everything else puts it in. Reads as "amount is
        # negative exactly when the type is an outflow". Zero is rejected
        # outright. Without this, a deposit of -500 is a valid row and every
        # cash-balance figure derived from transactions is quietly wrong.
        CheckConstraint(
            "amount <> 0 AND (amount < 0) = "
            f"(transaction_type IN ({', '.join(repr(t) for t in OUTFLOW_TYPES)}))",
            name="amount_sign_matches_type",
        ),
        Index("ix_transactions_account_id_trade_date", "account_id", "trade_date"),
        Index("ix_transactions_instrument_id", "instrument_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    account_id: Mapped[str] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False
    )
    # Null for cash movements: deposits, withdrawals and fees have no instrument.
    instrument_id: Mapped[str | None] = mapped_column(
        ForeignKey("instruments.id", ondelete="RESTRICT")
    )
    transaction_type: Mapped[str] = mapped_column(String(16), nullable=False)
    trade_date: Mapped[date] = mapped_column(Date, nullable=False)
    settle_date: Mapped[date | None] = mapped_column(Date)
    quantity: Mapped[Decimal | None] = mapped_column(_UNITS)
    unit_price: Mapped[Decimal | None] = mapped_column(_UNITS)
    # Signed: negative for money leaving the account.
    amount: Mapped[Decimal] = mapped_column(_AMOUNT, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="GBP")

    account: Mapped[Account] = relationship()
    instrument: Mapped[Instrument | None] = relationship()


class Price(Base):
    """Daily close prices. Composite primary key, no surrogate id."""

    __tablename__ = "prices"
    __table_args__ = (CheckConstraint("close > 0", name="close_positive"),)

    instrument_id: Mapped[str] = mapped_column(
        ForeignKey("instruments.id", ondelete="CASCADE"), primary_key=True
    )
    price_date: Mapped[date] = mapped_column(Date, primary_key=True)
    close: Mapped[Decimal] = mapped_column(_UNITS, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="GBP")

    instrument: Mapped[Instrument] = relationship()


class Task(Base, TimestampMixin):
    """Back-office task. Target of the LOW-tier `create_task` tool."""

    __tablename__ = "tasks"
    __table_args__ = (
        _in("status", TASK_STATUSES, "status"),
        Index("ix_tasks_status", "status"),
        Index("ix_tasks_client_id", "client_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    client_id: Mapped[str | None] = mapped_column(ForeignKey("clients.id", ondelete="SET NULL"))
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(16), nullable=False, server_default="open")
    due_date: Mapped[date | None] = mapped_column(Date)
    # "seed", a user id, or the agent that proposed it — useful when auditing
    # what the assistant created versus what a human did.
    created_by: Mapped[str | None] = mapped_column(Text)

    client: Mapped[Client | None] = relationship()
