"""Documents and chunks: the retrieval side of the schema (ARCHITECTURE section 4)."""

from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    BigInteger,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

# The schema's own truth, deliberately NOT read from settings: the column width
# is fixed when the migration runs, so making it env-dependent would let one
# machine autogenerate a migration that disagrees with the committed one.
# `settings.embedding_dimensions` is what we ask the embedding API for; a test
# asserts the two agree.
EMBEDDING_DIM = 1536


class Document(Base):
    """One source file. `sha256` drives incremental ingestion."""

    __tablename__ = "documents"

    # A slug such as "fee-schedule", referenced directly by eval datasets
    # (expected_sources) and by citations, so it must stay stable and readable.
    id: Mapped[str] = mapped_column(String(128), primary_key=True)

    # Deviation from ARCHITECTURE section 4, which lists only `id`: ingestion
    # needs to map a file on disk back to its document row to detect renames
    # and deletions, and the id is a slug rather than a path.
    source_path: Mapped[str] = mapped_column(Text, nullable=False, unique=True)

    title: Mapped[str | None] = mapped_column(Text)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default="1")
    page_count: Mapped[int | None] = mapped_column(Integer)
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    chunks: Mapped[list["Chunk"]] = relationship(
        back_populates="document", cascade="all, delete-orphan", passive_deletes=True
    )


class Chunk(Base):
    """An embedded passage. Carries both a vector and a tsvector for hybrid search."""

    __tablename__ = "chunks"
    __table_args__ = (
        UniqueConstraint("document_id", "chunk_index", name="document_chunk_index"),
        Index("ix_chunks_document_id", "document_id"),
        # Approximate nearest neighbour. Cosine, matching the distance used at
        # query time — an index built for a different operator is ignored.
        Index(
            "ix_chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        Index("ix_chunks_tsv", "tsv", postgresql_using="gin"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    document_id: Mapped[str] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False
    )

    # Ordinal within the document: lets retrieval widen context to neighbouring
    # chunks, and makes the unique constraint above meaningful.
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    page: Mapped[int | None] = mapped_column(Integer)
    content: Mapped[str] = mapped_column(Text, nullable=False)

    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))

    # Generated by Postgres, so it can never drift from `content`.
    tsv: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', content)", persisted=True),
        nullable=False,
    )

    # `metadata` is reserved by SQLAlchemy's declarative API (Base.metadata), so
    # the attribute is `meta` while the column keeps the documented name.
    meta: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, server_default="{}"
    )

    document: Mapped[Document] = relationship(back_populates="chunks")
