"""initial schema

Revision ID: 341235f4ba95
Revises: 1a6134fc13d0
Create Date: 2026-10-02 18:56:27.588057

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "341235f4ba95"
down_revision: str | Sequence[str] | None = "1a6134fc13d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column(
            "args", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("proposed_action", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("requested_by", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nulls(decided_at, decided_by) = CASE status WHEN 'pending' THEN 2 ELSE 0 END",
            name=op.f("ck_approvals_decision_fields_match_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired')",
            name=op.f("ck_approvals_status"),
        ),
        sa.CheckConstraint("tier IN ('READ', 'LOW', 'HIGH')", name=op.f("ck_approvals_tier")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        "ix_approvals_status_created_at", "approvals", ["status", "created_at"], unique=False
    )
    op.create_index("ix_approvals_thread_id", "approvals", ["thread_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("segment", sa.String(length=16), nullable=False),
        sa.Column("adviser", sa.Text(), nullable=True),
        sa.Column("onboarded_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "segment IN ('retail', 'affluent', 'hnw', 'uhnw')", name=op.f("ck_clients_segment")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("source_path", name=op.f("uq_documents_source_path")),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("ongoing_charge", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_class IN ('equity', 'bond', 'fund', 'etf', 'cash', 'alternative')",
            name=op.f("ck_instruments_asset_class"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
    )
    op.create_table(
        "usage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("route", sa.String(length=32), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0", name=op.f("ck_usage_tokens_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage")),
    )
    op.create_index("ix_usage_created_at", "usage", ["created_at"], unique=False)
    op.create_index("ix_usage_route", "usage", ["route"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("client_id", sa.String(length=16), nullable=False),
        sa.Column("account_type", sa.String(length=16), nullable=False),
        sa.Column("mandate", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("base_currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("opened_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('ISA', 'SIPP', 'GIA', 'JISA', 'TRUST')",
            name=op.f("ck_accounts_account_type"),
        ),
        sa.CheckConstraint(
            "mandate IN ('advisory', 'discretionary', 'execution_only')",
            name=op.f("ck_accounts_mandate"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'closed', 'suspended')", name=op.f("ck_accounts_status")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_accounts_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index("ix_accounts_client_id", "accounts", ["client_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column(
            "args", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("approval_id", sa.UUID(), nullable=True),
        sa.Column("approver", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('ok', 'error', 'denied')", name=op.f("ck_audit_log_outcome")
        ),
        sa.CheckConstraint("tier IN ('READ', 'LOW', 'HIGH')", name=op.f("ck_audit_log_tier")),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_audit_log_approval_id_approvals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_thread_id_created_at", "audit_log", ["thread_id", "created_at"], unique=False
    )
    op.create_index("ix_audit_log_tool_name", "audit_log", ["tool_name"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="document_chunk_index"),
    )
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"], unique=False)
    op.create_index(
        "ix_chunks_embedding_hnsw",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_chunks_tsv", "chunks", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "prices",
        sa.Column("instrument_id", sa.String(length=16), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.CheckConstraint("close > 0", name=op.f("ck_prices_close_positive")),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_prices_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "price_date", name=op.f("pk_prices")),
    )
    op.create_table(
        "risk_profiles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=16), nullable=False),
        sa.Column("tolerance", sa.String(length=16), nullable=False),
        sa.Column("investment_objective", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("horizon_years", sa.Integer(), nullable=True),
        sa.Column("capacity_for_loss", sa.String(length=16), nullable=True),
        sa.Column(
            "restrictions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("assessed_at", sa.Date(), nullable=True),
        sa.Column("next_review_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capacity_for_loss IN ('low', 'medium', 'high')",
            name=op.f("ck_risk_profiles_capacity_for_loss"),
        ),
        sa.CheckConstraint(
            "investment_objective IN ('income', 'growth', 'balanced', 'preservation')",
            name=op.f("ck_risk_profiles_investment_objective"),
        ),
        sa.CheckConstraint(
            "tolerance IN ('conservative', 'balanced', 'growth', 'aggressive')",
            name=op.f("ck_risk_profiles_tolerance"),
        ),
        sa.CheckConstraint("score BETWEEN 1 AND 100", name=op.f("ck_risk_profiles_score_range")),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_risk_profiles_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_profiles")),
        sa.UniqueConstraint("client_id", name=op.f("uq_risk_profiles_client_id")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=16), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'done', 'cancelled')", name=op.f("ck_tasks_status")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_tasks_client_id_clients"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_client_id", "tasks", ["client_id"], unique=False)
    op.create_index("ix_tasks_status", "tasks", ["status"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_holdings_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_holdings_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_holdings_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holdings")),
        sa.UniqueConstraint("account_id", "instrument_id", name="account_instrument"),
    )
    op.create_index("ix_holdings_account_id", "holdings", ["account_id"], unique=False)
    op.create_index("ix_holdings_instrument_id", "holdings", ["instrument_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.String(length=16), nullable=True),
        sa.Column("transaction_type", sa.String(length=16), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("settle_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount <> 0 AND (amount < 0) = (transaction_type IN ('buy', 'withdrawal', 'fee'))",
            name=op.f("ck_transactions_amount_sign_matches_type"),
        ),
        sa.CheckConstraint(
            "transaction_type IN ('buy', 'sell', 'dividend', 'fee', 'deposit', 'withdrawal')",
            name=op.f("ck_transactions_transaction_type"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_transactions_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_account_id_trade_date",
        "transactions",
        ["account_id", "trade_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_instrument_id", "transactions", ["instrument_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_instrument_id", table_name="transactions")
    op.drop_index("ix_transactions_account_id_trade_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_holdings_instrument_id", table_name="holdings")
    op.drop_index("ix_holdings_account_id", table_name="holdings")
    op.drop_table("holdings")
    op.drop_index("ix_tasks_status", table_name="tasks")
    op.drop_index("ix_tasks_client_id", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("risk_profiles")
    op.drop_table("prices")
    op.drop_index("ix_chunks_tsv", table_name="chunks", postgresql_using="gin")
    op.drop_index(
        "ix_chunks_embedding_hnsw",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_chunks_document_id", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_audit_log_tool_name", table_name="audit_log")
    op.drop_index("ix_audit_log_thread_id_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_accounts_client_id", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index("ix_usage_route", table_name="usage")
    op.drop_index("ix_usage_created_at", table_name="usage")
    op.drop_table("usage")
    op.drop_table("instruments")
    op.drop_table("documents")
    op.drop_table("clients")
    op.drop_index("ix_approvals_thread_id", table_name="approvals")
    op.drop_index("ix_approvals_status_created_at", table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
